image: golang:1.12

variables:
  GOFLAGS: -mod=vendor
  GO111MODULE: on

build:
  stage: build
  script:
    - make
    - mkdir -p bin
    - cp /go/bin/terraform-provider-icinga2 bin/
  artifacts:
    name: terraform-provider-icinga2
    paths:
    - bin
