image: golang:1.14

variables:
  GOFLAGS: -mod=vendor
  GOARCH: amd64

.build:
  stage: build
  script: 
    - go build -v -ldflags="-s -w" -o terraform-provider-icinga2-${GOOS}-${GOARCH}
  artifacts:
    paths: 
      - terraform-provider-icinga2-*

linux-amd64:
  extends: .build
  variables:
    GOOS: linux

darwin-amd64:
  extends: .build
  variables:
    GOOS: darwin